name: "Package Changelog"
description: "Automatically Generate a Markdown Table w/ Changelogs for NPM/Node/Yarn Package-lock.json Files for Release Notes."
author: "Shane"
branding:
  icon: "activity"
  color: "green"

inputs:
  path:
    description: "Location of Lock File"
    default: "package-lock.json"
  update:
    description: "Update Release Notes"
    default: "true"
  heading:
    description: "Release Notes Heading"
    default: "### Package Changes"
  toggle:
    description: "Toggle Text for Summary"
    default: "Click Here to View Changes"
  open:
    description: "Summary Open by Default"
    default: "false"
  empty:
    description: "Add Summary on No Changes"
    default: "false"
  columns:
    description: "Customize Table Columns"
    default: "n,i,t,b,a"
  sections:
    description: "Customize Package Sections"
    default: "a,u,d,r,k"
  max:
    description: "Max Releases to Process"
    default: "30"
  summary:
    description: "Add Workflow Job Summary"
    default: "true"
  token:
    description: "GitHub Token"
    default: ${{ github.token }}

outputs:
  json:
    description: "Changes JSON Object"
  markdown:
    description: "Changes Markdown Table"

runs:
  using: "node24"
  main: "dist/index.js"
